************* Module interface.common.sequence
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:37:0: R0901: Too many ancestors (10/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:52:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:52:4: E0302: The special method '__getitem__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:58:0: R0901: Too many ancestors (10/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:66:0: R0901: Too many ancestors (12/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:79:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:79:4: E0302: The special method '__contains__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:83:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:83:4: E0302: The special method '__lt__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:86:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:86:4: E0302: The special method '__le__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:89:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:89:4: E0302: The special method '__eq__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:92:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:92:4: E0302: The special method '__ne__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:95:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:95:4: E0302: The special method '__gt__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:98:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:98:4: E0302: The special method '__ge__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:101:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:101:4: E0302: The special method '__add__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:104:4: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:104:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:104:4: E0302: The special method '__mul__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:107:4: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:107:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:107:4: E0302: The special method '__rmul__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:111:8: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:119:0: R0901: Too many ancestors (13/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:122:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:125:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:131:0: E0239: Inheriting 'Interface', which is not a class. (inherit-non-class)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:131:0: R0901: Too many ancestors (8/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:134:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:134:4: E0302: The special method '__setitem__' expects 2 param(s), 1 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:141:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:141:4: E0302: The special method '__delitem__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:149:8: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:157:8: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:165:4: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:165:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:165:4: E0302: The special method '__iadd__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:168:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:171:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:174:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:177:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:180:4: E0211: Method has no argument (no-method-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:183:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:186:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:189:0: R0901: Too many ancestors (9/7) (too-many-ancestors)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:192:4: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:192:4: E0213: Method should have "self" as first argument (no-self-argument)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:192:4: E0302: The special method '__imul__' expects 1 param(s), 0 was given (unexpected-special-method-signature)
/log/firmware/firmware/usr/lib/python3.8/site-packages/zope/interface/common/sequence.py:195:0: R0901: Too many ancestors (15/7) (too-many-ancestors)

-------------------------------------
Your code has been rated at -46.50/10

