************* Module asyncio.base_subprocess
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:10:0: R0902: Too many instance attributes (10/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:12:4: R0913: Too many arguments (11/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:84:4: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:134:4: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:135:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:187:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:194:4: C0103: Argument name "cb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:200:4: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:204:4: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:259:8: C0103: Attribute name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:257:4: C0103: Argument name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:271:8: W0212: Access to a protected member _pipe_connection_lost of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:275:8: W0212: Access to a protected member _protocol of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:278:8: W0212: Access to a protected member _protocol of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/base_subprocess.py:285:8: W0212: Access to a protected member _pipe_data_received of a client class (protected-access)

-----------------------------------
Your code has been rated at 9.23/10

