************* Module multiprocessing.managers
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:110:0: C0325: Unnecessary parens after 'return' keyword (superfluous-parens)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1:0: C0302: Too many lines in module (1400/1000) (too-many-lines)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:45:0: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:67:36: C0103: Attribute name "id" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:60:0: R0205: Class 'Token' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:66:40: W0622: Redefining built-in 'id' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:83:0: W0102: Dangerous default value {} as argument (dangerous-default-value)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:83:0: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:83:0: C0103: Argument name "id" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:83:16: W0622: Redefining built-in 'id' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:94:4: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:101:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:137:0: R0205: Class 'Server' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:137:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:151:8: C0103: Variable name "Listener" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:151:18: C0103: Variable name "Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:151:18: W0612: Unused variable 'Client' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:167:8: W0212: Access to a protected member _manager_server of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:187:16: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:190:12: C0103: Variable name "t" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:194:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:206:15: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:211:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:217:15: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:217:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:220:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:203:12: W0612: Unused variable 'ignore' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:228:4: R0914: Too many local variables (25/15) (too-many-locals)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:293:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:247:16: C0103: Variable name "ke" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:252:24: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:264:23: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:264:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:285:27: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:301:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:299:23: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:299:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:301:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:251:20: W0612: Unused variable 'second_ke' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:228:4: R0912: Too many branches (16/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:228:4: R0915: Too many statements (59/50) (too-many-statements)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:309:32: W0613: Unused argument 'conn' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:309:38: W0613: Unused argument 'ident' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:309:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:312:27: W0613: Unused argument 'conn' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:312:33: W0613: Unused argument 'ident' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:312:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:315:28: W0613: Unused argument 'conn' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:315:34: W0613: Unused argument 'ident' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:315:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:324:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:327:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:327:25: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:343:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:343:32: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:350:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:357:8: W0702: No exception type(s) specified (bare-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:358:12: C0415: Import outside toplevel (traceback) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:394:12: W0622: Redefining built-in 'callable' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:363:4: E0211: Method has no argument (no-method-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:368:18: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:378:22: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:379:16: C0415: Import outside toplevel (warnings) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:386:16: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:388:16: C0415: Import outside toplevel (warnings) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:391:8: W0642: Invalid assignment to args in method (self-cls-assignment)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:394:49: W0612: Unused variable 'proxytype' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:363:4: R0912: Too many branches (14/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:426:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:426:26: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:432:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:440:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:444:12: C0103: Variable name "ke" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:440:21: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:453:20: W0612: Unused variable 'obj' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:453:25: W0612: Unused variable 'exposed' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:453:34: W0612: Unused variable 'gettypeid' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:458:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:458:21: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:166:8: W0201: Attribute 'stop_event' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:490:0: R0205: Class 'State' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:490:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:525:8: C0103: Attribute name "_Listener" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:525:24: C0103: Attribute name "_Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:509:0: R0205: Class 'BaseManager' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:509:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:533:12: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:547:18: C0103: Variable name "Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:547:8: W0612: Unused variable 'Listener' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:557:12: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:577:41: W0212: Access to a protected member _identity of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:596:4: R0913: Too many arguments (8/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:625:12: W0622: Redefining built-in 'id' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:625:12: C0103: Variable name "id" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:663:12: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:676:4: C0103: Argument name "_Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:676:26: W0621: Redefining name 'process' from outer scope (line 32) (redefined-outer-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:688:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:703:16: W0212: Access to a protected member _address_to_local of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:712:30: W0622: Redefining built-in 'callable' (redefined-builtin)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:712:4: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:730:23: C0123: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:731:23: C0123: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:740:29: W0212: Access to a protected member _create of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:742:27: W0212: Access to a protected member _serializer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:743:28: W0212: Access to a protected member _authkey of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:745:23: W0212: Access to a protected member _Client of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:745:59: W0212: Access to a protected member _authkey of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:572:8: W0201: Attribute '_process' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:637:16: W0201: Attribute '_process' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:588:8: W0201: Attribute 'shutdown' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:756:4: W0231: __init__ method from base class 'set' is not called (super-init-not-called)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:793:8: C0103: Attribute name "_Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:765:0: R0205: Class 'BaseProxy' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:765:0: R0902: Too many instance attributes (10/7) (too-many-instance-attributes)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:772:4: R0913: Too many arguments (8/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:773:31: W0613: Unused argument 'exposed' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:822:4: W0102: Dangerous default value {} as argument (dangerous-default-value)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:837:8: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:841:24: W0212: Access to a protected member _registry of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:869:34: W0212: Access to a protected member _state of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:879:4: C0103: Argument name "_Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:889:19: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:889:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:907:15: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:907:8: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:916:8: R1705: Unnecessary "else" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:917:30: E1101: Instance of 'BaseProxy' has no '_exposed_' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:937:15: W0703: Catching too general exception Exception (broad-except)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:944:0: C0103: Function name "RebuildProxy" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:965:0: W0102: Dangerous default value {} as argument (dangerous-default-value)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:965:0: C0103: Function name "MakeProxyType" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:978:8: W0122: Use of exec (exec-used)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:981:4: C0103: Variable name "ProxyType" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:982:4: W0212: Access to a protected member _exposed_ of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:987:0: C0103: Function name "AutoProxy" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:987:0: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:992:4: C0103: Variable name "_Client" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1002:18: W0212: Access to a protected member _authkey of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1006:4: C0103: Variable name "ProxyType" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1009:4: W0212: Access to a protected member _isauto of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1016:0: E0102: class already defined line 7 (function-redefined)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1016:0: R0205: Class 'Namespace' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1016:0: R0903: Too few public methods (1/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1028:0: E0102: class already defined line 10 (function-redefined)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1028:0: R0205: Class 'Value' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1029:40: W0613: Unused argument 'lock' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1040:0: E0102: function already defined line 22 (function-redefined)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1040:0: C0103: Function name "Array" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1040:30: W0613: Unused argument 'lock' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1078:4: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1180:0: W0212: Access to a protected member _method_to_typeid_ of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1194:0: W0212: Access to a protected member _method_to_typeid_ of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1211:0: E0102: class already defined line 25 (function-redefined)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1222:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1223:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1224:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1225:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1226:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1227:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1228:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1230:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1231:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1232:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1233:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1234:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1235:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1236:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1237:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1240:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1241:0: E1101: Class 'SyncManager' has no 'register' member (no-member)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1251:8: W0102: Dangerous default value [] as argument (dangerous-default-value)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1296:8: E0211: Method has no argument (no-method-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1312:23: E0602: Undefined variable 'self' (undefined-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1313:50: E0602: Undefined variable 'self' (undefined-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1303:16: W0612: Unused variable 'typeod' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1322:8: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1322:32: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1326:8: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1326:34: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1331:8: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1331:32: W0613: Unused argument 'c' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1356:16: C0415: Import outside toplevel (.resource_tracker) (import-outside-toplevel)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1363:12: W0107: Unnecessary pass statement (unnecessary-pass)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1368:16: R1720: Unnecessary "elif" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1378:8: C0103: Method name "SharedMemory" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1385:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1390:8: C0103: Method name "ShareableList" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1394:16: C0103: Variable name "sl" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/multiprocessing/managers.py:1397:16: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)

-----------------------------------
Your code has been rated at 6.41/10

