************* Module asyncio.unix_events
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1:0: C0302: Too many lines in module (1389/1000) (too-many-lines)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:44:4: W0107: Unnecessary pass statement (unnecessary-pass)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:42:21: W0613: Unused argument 'signum' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:42:29: W0613: Unused argument 'frame' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:97:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:118:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:119:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:128:11: W0212: Access to a protected member _cancelled of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:152:12: R1720: Unnecessary "else" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:153:16: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:165:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:185:4: R0913: Too many arguments (9/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:210:22: W0212: Access to a protected member _wait of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:216:34: W0212: Access to a protected member _process_exited of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:215:38: W0613: Unused argument 'pid' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:299:16: R1720: Unnecessary "else" after "raise" (no-else-raise)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:323:12: W0212: Access to a protected member _start_serving of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:263:4: R0912: Too many branches (16/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:333:8: W0612: Unused variable 'exc' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:338:8: W0612: Unused variable 'err' (unused-variable)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:353:4: R0913: Too many arguments (9/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:355:8: C0103: Variable name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:406:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:383:20: C0123: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:353:4: R0912: Too many branches (16/12) (too-many-branches)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:423:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:428:8: C0103: Function name "cb" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:430:16: C0103: Variable name "fd" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:440:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:505:16: W0212: Access to a protected member _remove_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:513:8: W0212: Access to a protected member _remove_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:521:8: W0212: Access to a protected member _add_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:559:8: W0212: Access to a protected member _remove_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:572:30: W0212: Access to a protected member _FlowControlMixin of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:575:4: R0913: Too many arguments (6/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:670:19: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:665:16: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:667:16: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:674:12: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:678:12: W0212: Access to a protected member _add_writer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:692:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:687:12: C0103: Variable name "n" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:697:12: W0212: Access to a protected member _remove_writer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:700:12: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:702:16: W0212: Access to a protected member _remove_writer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:705:20: W0212: Access to a protected member _remove_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:711:4: R0201: Method could be a function (no-self-use)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:720:12: W0212: Access to a protected member _remove_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:762:12: W0212: Access to a protected member _remove_writer of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:764:8: W0212: Access to a protected member _remove_reader of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:774:12: W0201: Attribute '_loop' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:779:4: R0913: Too many arguments (7/5) (too-many-arguments)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:789:12: W0201: Attribute '_proc' defined outside __init__ (attribute-defined-outside-init)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:777:0: R0903: Too few public methods (0/2) (too-few-public-methods)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:876:4: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:876:4: C0103: Argument name "b" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:876:4: C0103: Argument name "c" doesn't conform to snake_case naming style (invalid-name)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:882:4: R1705: Unnecessary "elif" after "return" (no-else-return)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:938:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1022:0: W0223: Method '_do_waitpid' is abstract in class 'BaseChildWatcher' but is not overridden (abstract-method)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1157:15: W0143: Comparing against a callable, did you omit the parenthesis? (comparison-with-callable)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1244:15: W0703: Catching too general exception BaseException (broad-except)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1239:24: W0613: Unused argument 'signum' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1239:32: W0613: Unused argument 'frame' (unused-argument)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1346:13: W0212: Access to a protected member _lock of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1350:30: W0212: Access to a protected member _MainThread of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1351:46: W0212: Access to a protected member _loop of a client class (protected-access)
/log/firmware/firmware/usr/lib/python3.8/asyncio/unix_events.py:1364:55: W0212: Access to a protected member _MainThread of a client class (protected-access)

-----------------------------------
Your code has been rated at 9.16/10

